### ISSUE TITLE
Was soll in Datei app-overview.md dokumentiert werden?

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.default.template#4]
**Frage:**
Was soll in Datei app-overview.md (Ordner doc/app) dokumentiert werden? Laut ReadMe.md ist dieses Repository als Vorlage für NICHT App-Projekte gedacht, also gibt es auch nicht app-spezifisches zu dokumentieren?

**Comment by Bauer-David** [comment]
Ja Stimmt, ich lösch den app Ordner

**Comment by Bauer-David** [comment]
Ich habe die doc/ Ordnerstruktur angepasst
